text_file = open("./read_it.txt", "r")
# print(text_file)
# whole_things = text_file.read()
# print(whole_things)
# print(text_file.readline(1))
print(f"Opening and closing the file.\n\nReading characters from the file.\n{text_file.read(1)}\n{text_file.read(5)}\n")
text_file.close()
text_file = open("./read_it.txt", "r")
print(f"Reading the entire file at once.\n{text_file.read()}\n")
text_file.close()
text_file = open("./read_it.txt", "r")
print(f"Reading characters from a line.\n{text_file.readline(1)}\n{text_file.readline(5)}\n")
text_file.close()
text_file = open("./read_it.txt", "r")
print(f"Reading one line at a time.\n{text_file.readline()}\n{text_file.readline()}\n{text_file.readline()}\n")
text_file.close()
text_file = open("./read_it.txt", "r")
print(f"Reading the entire file into a list.\n{text_file.readlines()}")
text_file.close()
text_file = open("./read_it.txt", "r")
print(f"{len(text_file.readlines())}")
text_file.close()
text_file = open("./read_it.txt", "r")
for line in text_file:
    print(line)
print()
text_file.close()
text_file = open("./read_it.txt", "r")
print("Looping through the file, line by line.")
for line in text_file:
    print(line)
print()
text_file.close()
print()
input("Press the enter key to exit.")